const messages = {
  ACCOUNT_BLOCKED: "Your account is blocked.",
  INVALID_EMAIL_PASSWORD: "Invalid email and password.",
  LOGIN_SUCCESS: "Login Successfully.",
  INVALID_PASSWORD: "Please enter a valid password.",
  EMAIL_EXIST: "Email already exists.",
  REGISTER_SUCCESS: "User registered successfully.",
  OTP_SEND: "OTP is send in your mail.Please check mail.",
  INVALID_EMAIL: "Invalid email.",
  OTP_VERIFY: "OTP verify succesfully.",
  INVALID_OTP: "Invalid OTP.",
  RESEND_OTP: "Please resend OTP.",
  RESET_PASSWORD: "Password reset succesfully.",
  NO_DATA_FOUND: "No data found.",
  LOGOUT_SUCCESS: "Logout succesfully.",
  RECORD_EXIST: "Already exists.",
  ADD_LOCATION: "Location added succesfully.",
  DELETE_LOCATION: "Location deleted succesfully.",
  UPDATE_LOCATION: "Location updated successfully.",
  PROFILE_UPDATE: "Profile Updated.",
  ALREADY_EXIST: "Email or phone number already exists.",
  ADD_STAFF: "Staff added succesfully.",
  DELETE_STAFF: "Staff deleted succesfully.",
  UPDATE_STAFF: "Staff updated successfully.",
  UPDATE_STAFF_PERMISSION: "Staff permission updated successfully.",
  ADD_LEAD_STATUS: "Lead Status added succesfully.",
  DELETE_LEAD_STATUS: "Lead Status deleted succesfully.",
  UPDATE_LEAD_STATUS: "Lead Status updated successfully.",
  ADD_UNIVERSITY: "University added succesfully.",
  DELETE_UNIVERSITY: "University deleted succesfully.",
  UPDATE_UNIVERSITY: "University updated successfully.",
  ADD_COURSE_TYPE: "Course Type added succesfully.",
  DELETE_COURSE_TYPE: "Course Type deleted succesfully.",
  UPDATE_COURSE_TYPE: "Course Type updated successfully.",
  ADD_LOAN_TYPE: "Loan Type added succesfully.",
  DELETE_LOAN_TYPE: "Loan Type deleted succesfully.",
  UPDATE_LOAN_TYPE: "Loan Type updated successfully.",
  ADD_STUDENT: "Student added succesfully.",
  DELETE_STUDENT: "Student deleted succesfully.",
  UPDATE_STUDENT: "Student updated successfully.",
  UPDATE_NOTIFICATION: "Notification updated successfully.",
  ADD_PARTNER: "Partner added succesfully.",
  DELETE_PARTNER: "Partner deleted succesfully.",
  UPDATE_PARTNER: "Partner updated successfully.",
};

module.exports = messages;
